parameters:
    flex_workflow.installer.composer.class: EzSystems\EzStudioUpgradeBundle\Bundles\FlexWorkflow\Composer
    flex_workflow.installer.kernel.class: EzSystems\EzStudioUpgradeBundle\Bundles\FlexWorkflow\Kernel
    flex_workflow.installer.database.class: EzSystems\EzStudioUpgradeBundle\Bundles\FlexWorkflow\Database
    flex_workflow.installer.routing.class: EzSystems\EzStudioUpgradeBundle\Bundles\FlexWorkflow\Routing

services:
    flex_workflow.installer:
        class: "%ezstudio_upgrade.bundle.class%"
        calls:
            - [ addInstaller, ["@flex_workflow.installer.composer"] ]
            - [ addInstaller, ["@flex_workflow.installer.kernel"] ]
            - [ addInstaller, ["@flex_workflow.installer.database"] ]
            - [ addInstaller, ["@flex_workflow.installer.routing"] ]
        tags:
            - { name: ezstudio_upgrade.bundle, bundle: "Flex Workflow" }

    flex_workflow.installer.composer:
        class: "%flex_workflow.installer.composer.class%"

    flex_workflow.installer.routing:
        class: "%flex_workflow.installer.routing.class%"
        arguments:
            - "@flex_workflow.installer.kernel"

    flex_workflow.installer.kernel:
        class: "%flex_workflow.installer.kernel.class%"
        arguments:
            - "@kernel"

    flex_workflow.installer.database:
        class: "%flex_workflow.installer.database.class%"
        arguments:
            - "@ezpublish.api.storage_engine.legacy.dbhandler"
